### ISSUE TITLE
Internacionalização

### ISSUE THREAD

**Issue by cogumm** [pabloVinicius/covid-19-dashboard#1]
Para a internacionalização estava pensando em utilizar este framework [i18next](https://github.com/i18next/i18next), o que me diz ?

Assim já seriam duas tarefas ao mesmo tempo.

- [ ] Other languages translations
- [ ] Portuguese translation

**Comment by pabloVinicius** [comment]
Acho que é uma boa. Viu a versão dele pra [react](https://github.com/i18next/react-i18next)? É uma boa porque tem suporte à hooks e react suspense

**Comment by islanrodrigues** [comment]
@cogumm cara, como está o andamento disto? 
Se você achar conveniente, posso te dar um apoio nessa tarefa.

**Comment by cogumm** [comment]
> @cogumm cara, como está o andamento disto?
> Se você achar conveniente, posso te dar um apoio nessa tarefa. Acredito que o uso do [i18n](https://github.com/i18next/react-i18next) seja bastante interessante mesmo.

Infelizmente não consegui dar continuidade ontem.
Se quiser assumir a tarefa, fica à vontade.

**Comment by islanrodrigues** [comment]
> > @cogumm cara, como está o andamento disto?
> > Se você achar conveniente, posso te dar um apoio nessa tarefa. Acredito que o uso do [i18n](https://github.com/i18next/react-i18next) seja bastante interessante mesmo.
> 
> Infelizmente não consegui dar continuidade ontem.
> Se quiser assumir a tarefa, fica à vontade.

Tranquilo. Irei dar início a essa tarefa.

**Comment by islanrodrigues** [comment]
Tranquilo. Darei início a esta tarefa.
